### ISSUE TITLE
Outdated example?

### ISSUE THREAD

**Issue by dr-thca** [BatchLabs/Batch-ReactNative-Plugin-Sample#1]
Our team is using Batch and React Navigation for a project and have had some struggles with deeplinks not opening correctly. 

According to the React Navigation Deeplinking [docs](https://reactnavigation.org/docs/deep-linking/#third-party-integrations) you need a `subscribe` method that adds an eventlistener. In this example an eventlistener is added https://github.com/BatchLabs/Batch-ReactNative-Plugin-Sample/blob/68c92d522b7d63916d5c28727483a455da03283b/app/components/useLinking.ts#L8-L39 The `useLinking` is unused because you use React Navigation in this example repo:

https://github.com/BatchLabs/Batch-ReactNative-Plugin-Sample/blob/68c92d522b7d63916d5c28727483a455da03283b/app/components/StackNavigator.tsx#L15-L18

The React Navigation integration is shown here:
 https://github.com/BatchLabs/Batch-ReactNative-Plugin-Sample/blob/68c92d522b7d63916d5c28727483a455da03283b/app/App.tsx#L27-L41
but is missing a `subscribe` method.

My question is if that is on purpose? Is the `subscribe` object not neccessary? 

I'm unsure since both the Batch documentation and the React Navigation docs recommend an eventListener:
<img width="951" alt="image" src="https://github.com/BatchLabs/Batch-ReactNative-Plugin-Sample/assets/157373281/672fd476-47f4-46dd-b709-7cbd38b4027e">
https://doc.batch.com/react-native/advanced/deeplinking/#doc_page_title

<img width="668" alt="image" src="https://github.com/BatchLabs/Batch-ReactNative-Plugin-Sample/assets/157373281/e4516c2f-bef5-4d71-9e6b-288953e637f6">

https://reactnavigation.org/docs/deep-linking/#third-party-integrations

**Comment by dr-thca** [comment]
I did some more research, and it seems like React Navigation handles the eventListener by default. The docs should probably be updated as to avoid more confusion. After telling the rest of the team about this they told me that they had the same misunderstanding just a few months ago.

**Comment by arnaud-roland** [comment]
Hi,
Yes, react-native navigation will directly handle the deeplink following your configuration. Thanks for the report, we will update our documentation to avoid misunderstanding in the future.
